### ISSUE TITLE
Current tab is duplicated when boosting

### ISSUE THREAD

**Issue by eloydegen** [rugk/mastodon-simplified-federation#117] opened 2023-08-21 10:41 UTC
## Bug description
When installing the plugin and clicking on boost on a different mastodon server, it opens a new tab of the different server instead of boosting the post to my profile.

I have an account on a Mastodon glitch-soc instance, https://hsnl.social

## Steps to reproduce
1. Install extension and make sure my handle is filled in in the settings
2. Go to different server
3. Boost post
4. Current tab is duplicated

## System
* Plugin: 2.1
* Firefox: 109
* Fedora Linux 36

**Comment by rugk** [comment] 2023-08-21 17:54
Hi and thanks for your bug report. Does this _always_ happen or only sometimes? I have experienced something like that too, but it did not happen that often… 

Could you provide a concrete link/URL to the toot, please?

**Comment by austinhuang0131** [comment] 2023-10-07 19:27
By "Current tab is duplicated" does it add the fragment `#interact` at the end of the URL?

If so then fixed by #115

**Comment by willhansen** [comment] 2023-12-10 02:31
> By "Current tab is duplicated" does it add the fragment `#interact` at the end of the URL?
> 
> If so then fixed by #115

I'm running into this months after it's been fixed.  Probably because the version Firefox has on the addon page is 4 months old:
![Selection_411](https://github.com/rugk/mastodon-simplified-federation/assets/2918280/f69520f7-0e57-44bb-b8d6-e68aa8606b13)

**Comment by rugk** [comment] 2024-01-01 21:06
Fair enough, I have [released v2.2](https://github.com/rugk/mastodon-simplified-federation/releases/tag/v2.2). Could you try it again with this version?

I assume the issue is fixed, so I'll close it for now.

**Closed by rugk** 2024-01-01 21:06 UTC
Labels: bug

**Comment by eloydegen** [comment] 2024-01-02 19:17
Yeah, it's fixed, thank you! And sorry for forgetting to reply earlier.
