### ISSUE TITLE
Experiment with protocol handlers

### ISSUE THREAD

**Issue by SoniEx2** [rugk/mastodon-simplified-federation#33] opened 2019-06-07 11:16 UTC
## Background

It appears this addon is trying to do something I'm trying to do more generally in https://github.com/whatwg/html/issues/4584, as such I'd like you to integrate my idea into it.

## Proposed solution

It'd be easiest to just integrate my idea into the addon

## Alternatives

The main alternative is to get both mainstream browsers and upstream mastodon to support https://github.com/whatwg/html/issues/4584, but I haven't had any luck with that on the browser end at least.

## Additional context

It'd be cool if users of my software ( https://ganarchy.autistic.space/ ) benefitted from this addon. My software is also federated (for some definition of federated), so it would seem to make sense to support it as well.

**Comment by rugk** [comment] 2019-06-07 16:00
I think you may have actually had the same idea as we recently discussed in https://github.com/rugk/mastodon-simplified-federation/issues/31, so @wiktor-k may also be interested in this.
We also discussed a fallback for `web+mastodon:` explicitly…

> https://ganarchy.autistic.space/ 

Regarding that, please open a new issue on how it can be integrated, if you want to think it is possible in the current way. (i.e. I only redirect _from_  that follow buttons or so – I could not find any on that site.) 
Also the site you link to lists three projects actually…

**Comment by SoniEx2** [comment] 2019-06-07 16:07
I think just parse tags like `<meta protocol="PROTOCOL" default="DEFAULT?url=%s" />`.

e.g. `<meta protocol="web+mastodon" default="https://joinmastodon.org/">` or `<meta protocol="web+mastodon" default="/remote_action?url=%s">`.

(this can be done, right?)

then on the addon just provide a list of toggles to toggle them on and off (unless there's an API to detect protocol handlers? well in any case there's always the hack of registering the extension itself as a protocol handler for the relevant protocols and doing some back-and-forth with the UI, I guess, altho that doesn't work on mobile (yet).). oh and filter the `protocol` attribute so only a handful of approved protocols (basically `web+[...]` and a handful of others) can be shoved in it.

**Comment by SoniEx2** [comment] 2019-06-07 16:09
(`<meta protocol="https" default="http://leak-the-target.example.com/?url=%s" />` MUST NOT be allowed)

**Comment by rugk** [comment] 2019-06-07 16:30
Well… all this has been discussed in https://github.com/rugk/mastodon-simplified-federation/issues/31 already, and if you read the thread again, you see we have considered HTML parsing.

However, in the end, it makes only sense, when such a fallback is standardized. I doubt many website/Fediverse app devs will implement such a HTML markup just because of a tiny browser add-on as mine.
Also, when the add-on is installed, you obviously do not need any fallback, because the add-on can redirect it all. So the only case for the fallback would be if the add-on is _not_ installed – and this is a situation the add-on cannot influence.

Also you brought up an example, where such things can be risky. (though I did not think about that example/do not want to evaluate it now.)

In the end, the only actionable thing I could do is https://github.com/rugk/mastodon-simplified-federation/issues/33, basically, i.e. support the actual protocol handlers.

So again, I see nothing actionable I can do here, so I'll close this issue.
That said, thanks for opening https://github.com/whatwg/html/issues/4584 at WHATWG. This is certainly the (only) way forward for better usability when clicking Fediverse links. (and could make this add-on obsolete, after all :smile:)

**Comment by rugk** [comment] 2019-06-07 16:30
Duplicate of https://github.com/rugk/mastodon-simplified-federation/issues/31

**Closed by rugk** 2019-06-07 16:30 UTC
Labels: enhancement
