### ISSUE TITLE
Support for Firefox Mobile?

### ISSUE THREAD

**Issue by kr428** [rugk/mastodon-simplified-federation#100] opened 2023-03-13 14:29 UTC
Title probably says it all: Would it be possible to support this addon on Firefox Mobile (Android) as well?

**Comment by rugk** [comment] 2023-03-26 12:16
It already is technically. It is, due to design decisions by Mozilla at this point of time, currently somewhat difficult to do so, given only a hardcoded list of add-ons can be installed in Firefox for Android. See https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android#w_expanded-extension-support-in-firefox-for-android-nightly for how you can create your own list and use it in Android.

Firefox for iOS has no add-on support yet.

More information in 
https://github.com/rugk/mastodon-simplified-federation/issues/78.

**Comment by rugk** [comment] 2023-03-26 12:16
Duplicate of 
https://github.com/rugk/mastodon-simplified-federation/issues/78

**Closed by rugk** 2023-03-26 12:16 UTC
Labels: enhancement
